import 'features/slider/slider'
import 'components/main-hero/main-hero'
import 'components/products-showcase/products-showcase'
import 'components/reviews-list/reviews-list.js'
import 'components/reviews-list/text/text-reviews.js'
