import 'ui/popups/video-review/video-review.js'
import 'ui/popups/text-review/text-review.js'
import 'ui/popups/send-review/send-review.js'
import 'ui/content/content.js'
import 'ui/range-slider/range-slider'
import 'ui/popups/filter-popup/filter-popup'

import 'components/reviews-list/reviews-list.js'
import 'components/reviews-list/text/text-reviews.js'
import 'components/products-slider/products-slider.js'
